name: 'Tiny Tapeout Gate Level test'
description: 'This action will copy the GL netlist from the GDS action and run your testbench on it'
branding:
  color: purple
  icon: check
inputs:
  test-dir:
    description: 'The directory with the Makefile for running the tests'
    required: true
    default: 'test'

runs:
  using: 'composite'
  steps:
    - name: Download GDS artifact
      uses: actions/download-artifact@v4
      with:
        name: tt_submission

    - name: Set up environment variables
      shell: bash
      run: |
        cat << EOF >> $GITHUB_ENV
        PDK_ROOT=/home/runner/pdk
        PDK=sky130A
        EOF

    - name: Install Sky130 PDK
      uses: TinyTapeout/volare-action@v2
      with:
        pdk_name: sky130
        pdk_version: cd1748bb197f9b7af62a54507de6624e30363943
        pdk_root: /home/runner/pdk

    - name: Install iverilog
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y iverilog

    - name: Run tests
      shell: bash
      run: |
        cp tt_submission/*.v "${{ inputs.test-dir }}/gate_level_netlist.v"
        cd "${{ inputs.test-dir }}"
        rm -f tb.vcd
        make clean
        GATES=yes make

    - name: Upload VCD
      if: always()
      uses: actions/upload-artifact@v4
      with:
          name: gatelevel_test_vcd
          path: |
            ${{ inputs.test-dir }}/tb.vcd
            ${{ inputs.test-dir }}/results.tap

    - name: Test Summary
      if: always()
      uses: test-summary/action@v2.3
      with:
        paths: ${{ inputs.test-dir }}/results.tap
